# Permalinks
permalink:           pretty

# Setup
title:               Lisa VanderVoort
tagline:             Data Scientist
url:                 http://lvandervoort89.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Lisa VanderVoort
  email:             lisa.vandervoort@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/lvandervoort89

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
